import Head from "next/head";
import Link from "next/link";
import { api } from "n/utils/api";
import DefaultLayout from "n/components/Layout";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Home
      </div>
    </>
  );
}
