import Head from "next/head";
import { api } from "n/utils/api";

export default function Home() {
  const authors = api.author.getAll.useQuery()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {console.log(authors.data)}
      </div>
    </>
  );
}
